### ISSUE TITLE
What wrong my code? 

### ISSUE THREAD

**Issue by kaflan** [joecohens/laravel-elixir-webpack#13]
```
var elixir = require('laravel-elixir');
require("laravel-elixir-webpack");
var webpackConf = require(__dirname + '/webpack.config.js');
/*
 |--------------------------------------------------------------------------
 | Elixir Asset Management
 |--------------------------------------------------------------------------
 |
 | Elixir provides a clean, fluent API for defining some basic Gulp tasks
 | for your Laravel application. By default, we are compiling the Sass
 | file for our application, as well as publishing vendor resources.
 |
 */
elixir(function(mix) {
  mix.webpack("index.js");
});
```

 i run in console gulp and see 

```
/home/kaflan/Documents/test/test-app/gulpfile.js:18
  mix.webpack("index.js");
      ^

TypeError: mix.webpack is not a function
    at /home/kaflan/Documents/test/test-app/gulpfile.js:18:7
    at Elixir (/home/kaflan/Documents/test/test-app/node_modules/laravel-elixir/index.js:3:5)
    at Object.<anonymous> (/home/kaflan/Documents/test/test-app/gulpfile.js:17:1)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Liftoff.handleArguments (/usr/lib/node_modules/gulp/bin/gulp.js:116:3)
```

**Comment by morilog** [comment]
did you install `laravel-elixir-webpack` by `npm install laravel-elixir-webpack --save-dev`?

**Comment by izziaraffaele** [comment]
same here after upgrading to elixir 4

**Comment by tijanmdr** [comment]
@morilog I did install `laravel-elixir-webpack` as a `devDependencies`
