### ISSUE TITLE
Cannot find module 'underscore'

### ISSUE THREAD

**Issue by mattdeclaire** [joecohens/laravel-elixir-webpack#17]
My `package.json`:

```
{
  "private": true,
  "devDependencies": {
    "gulp": "^3.8.8",
    "laravel-elixir-webpack": "^0.2.3",
    "webpack": "^1.12.13"
  },
  "dependencies": {
    "laravel-elixir": "^4.0.0",
    "bootstrap-sass": "^3.0.0"
  }
}
```

Ran `npm install`, then `gulp` and got:

```
$ gulp
module.js:338
    throw err;
          ^
Error: Cannot find module 'underscore'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/matt/Sites/leagues/node_modules/laravel-elixir-webpack/index.js:4:9)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
```

Shouldn't `underscore` be a regular dependency?

**Comment by joecohens** [comment]
Fixed https://github.com/joecohens/laravel-elixir-webpack/commit/9d9546c9cb49d8a59cef599cd91986faf252659c

@mattdeclaire Thanks!
