### ISSUE TITLE
Elixir.GulpPaths is not a function

### ISSUE THREAD

**Issue by 74sharlock** [joecohens/laravel-elixir-webpack#20]
```
TypeError: Elixir.GulpPaths is not a function
    at prepGulpPaths (D:\workspace\newWifi\node_modules\laravel-elixir-webpack\index.js:55:12)
    at Object.webpack (D:\workspace\newWifi\node_modules\laravel-elixir-webpack\index.js:14:17)
    at D:\workspace\newWifi\gulpfile.js:19:9
    at Elixir (D:\workspace\newWifi\node_modules\laravel-elixir\index.js:3:5)
    at Object.<anonymous> (D:\workspace\newWifi\gulpfile.js:16:1)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
```

nodejs:  v5.9.0
npm: 3.7.3

and the gulpfile.js like this:

``` javascript
var elixir  = require('laravel-elixir');
require('laravel-elixir-webpack');

elixir(function(mix) {
    mix.webpack('b.js', {
        module: {
            loaders: [
                { test: /\.js$/, loader: 'babel?presets[]=es2015' }
            ]
        }
    });
});
```

Is there anything wrong?

**Comment by joecohens** [comment]
Hey! What version of Laravel Elixir are you using?

**Comment by 74sharlock** [comment]
@joecohens "1.0.3"

**Comment by 74sharlock** [comment]
@joecohens &operating systems: window 7 sp1 - 64bit

**Comment by joecohens** [comment]
@74sharlock Sorry, this plugin only works for Laravel Elixir 4 or greater

**Comment by 74sharlock** [comment]
@joecohens Yes! U're right ! <b>I got [Laravel Elixir] up to 5.0.0</b>, and it works.<b> Thanks a lot!</b>

**Comment by joecohens** [comment]
:beers:
